import '@testing-library/jest-dom';

// Mock the environment variables
vi.mock('../vite-env.d.ts', () => ({
  VITE_SUPABASE_ANON_KEY: 'test-anon-key',
  VITE_SUPABASE_URL: 'https://test.supabase.co',
  VITE_BREVO_API_KEY: 'test-brevo-key',
  VITE_API_URL: 'http://localhost:3000/api'
}));

// Mock window.location
Object.defineProperty(window, 'location', {
  value: { href: '' },
  writable: true
});

// Mock framer-motion to avoid animation issues in tests
vi.mock('framer-motion', async () => {
  return {
    motion: {
      div: 'div',
      form: 'form',
      h1: 'h1',
      h2: 'h2',
      h3: 'h3',
      p: 'p',
      span: 'span',
      ul: 'ul',
      li: 'li',
      button: 'button',
      a: 'a',
      section: 'section',
      article: 'article',
      header: 'header',
      footer: 'footer',
      nav: 'nav',
      main: 'main',
      aside: 'aside',
      figure: 'figure',
      img: 'img',
      input: 'input',
      textarea: 'textarea',
      select: 'select',
      option: 'option',
      label: 'label',
      fieldset: 'fieldset',
      legend: 'legend',
      table: 'table',
      tr: 'tr',
      td: 'td',
      th: 'th',
      thead: 'thead',
      tbody: 'tbody',
      tfoot: 'tfoot',
      caption: 'caption',
      col: 'col',
      colgroup: 'colgroup',
      svg: 'svg',
      path: 'path',
      g: 'g',
      defs: 'defs',
      mask: 'mask',
      pattern: 'pattern',
      use: 'use',
      circle: 'circle',
      rect: 'rect',
      line: 'line',
      polyline: 'polyline',
      polygon: 'polygon',
      ellipse: 'ellipse',
      text: 'text',
      tspan: 'tspan',
      animate: 'animate',
      animateMotion: 'animateMotion',
      animateTransform: 'animateTransform',
      set: 'set',
      linearGradient: 'linearGradient',
      radialGradient: 'radialGradient',
      stop: 'stop',
      clipPath: 'clipPath',
      filter: 'filter',
      feBlend: 'feBlend',
      feColorMatrix: 'feColorMatrix',
      feComponentTransfer: 'feComponentTransfer',
      feComposite: 'feComposite',
      feConvolveMatrix: 'feConvolveMatrix',
      feDiffuseLighting: 'feDiffuseLighting',
      feDisplacementMap: 'feDisplacementMap',
      feDistantLight: 'feDistantLight',
      feDropShadow: 'feDropShadow',
      feFlood: 'feFlood',
      feFuncA: 'feFuncA',
      feFuncB: 'feFuncB',
      feFuncG: 'feFuncG',
      feFuncR: 'feFuncR',
      feGaussianBlur: 'feGaussianBlur',
      feImage: 'feImage',
      feMerge: 'feMerge',
      feMergeNode: 'feMergeNode',
      feMorphology: 'feMorphology',
      feOffset: 'feOffset',
      fePointLight: 'fePointLight',
      feSpecularLighting: 'feSpecularLighting',
      feSpotLight: 'feSpotLight',
      feTile: 'feTile',
      feTurbulence: 'feTurbulence',
      foreignObject: 'foreignObject',
      marker: 'marker',
      symbol: 'symbol',
      view: 'view',
    },
    AnimatePresence: ({ children }) => children,
  };
});